name: CMake  

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu]
        conf: [release, debug]
        arch: [x64, x86]

    env:
      CMAKE_PRESET: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.conf }}
    
    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Windows compiler
      if: ${{ matrix.os }} == 'windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}

    - name: Configure CMake
      run: cmake --preset ${{ env.CMAKE_PRESET }}

    - name: Build
      run: cmake --build --preset ${{ env.CMAKE_PRESET }}

    - name: Test
      run: ctest --preset ${{ env.CMAKE_PRESET }}
  
